execute pathogen#infect()
syntax on
filetype plugin indent on

set number
set tabstop=2
set shiftwidth=2
set autoindent
colo murphy


set statusline+=%#warningmsg#
set statusline+=%{SyntasticStatuslineFlag()}
set statusline+=%*

let g:syntastic_always_populate_loc_list = 1
let g:syntastic_auto_loc_list = 1
let g:syntastic_check_on_open = 1
let g:syntastic_check_on_wq = 0

map <C-b> 		:NERDTreeToggle<CR>
map <C-o> 		:e
map <A-Left>  :tabprevious<CR>
map <A-Right> :tabNext<CR>
map <C-t>     :tabnew<CR>
map <C-w>     :tabclose<CR>
map <C-\>  		:!

autocmd bufenter * if (winnr("$") == 1 && exists("b:NERDTree") && b:NERDTree.isTabTree()) | q | endif

